### DISCUSSION TITLE
Best way to position a FAB on bottom right

### DISCUSSION THREAD

**Discussion by treeder** [material-components/material-web#5278] [Q&A]
The docs don't say how to position it, but I was wondering if there's something built in to position it to the bottom right and be sticky there.

**Comment by datvm** [comment]
Usually I use a flex box like [this](https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy50cyIsImNvbnRlbnQiOiJpbXBvcnQgXCJAbWF0ZXJpYWwvd2ViL2FsbFwiIn0seyJuYW1lIjoiaW5kZXguaHRtbCIsImNvbnRlbnQiOiI8IURPQ1RZUEUgaHRtbD5cbjxoZWFkPlxuICA8c2NyaXB0IHR5cGU9XCJtb2R1bGVcIiBzcmM9XCIuL3NpbXBsZS1ncmVldGluZy5qc1wiPjwvc2NyaXB0PlxuPC9oZWFkPlxuPGJvZHkgc3R5bGU9XCJtaW4taGVpZ2h0OiAxMDB2aDsgZGlzcGxheTogZmxleDsgZmxleC1kaXJlY3Rpb246IGNvbHVtbjtcIj5cbiAgPGRpdiBzdHlsZT1cImZsZXgtZ3JvdzogMTsgZGlzcGxheTogZmxleDsgZmxleC1kaXJlY3Rpb246IGNvbHVtbjtcIj5cbiAgICA8cD5Zb3VyIGNvbnRlbnQ8L3A-XG4gICAgXG4gICAgPGRpdiBzdHlsZT1cIm1hcmdpbi10b3A6IGF1dG87IG1hcmdpbi1ib3R0b206IDFyZW07IHRleHQtYWxpZ246IGVuZDtcIj5cbiAgICAgIDxtZC1mYWIgbGFiZWw9XCJZb3VyIEZBQlwiIHN0eWxlPVwibWFyZ2luLWJvdHRvbTogMXJlbTtcIj48L21kLWZhYj5cbiAgICA8L2Rpdj4gICAgXG4gIDwvZGl2PlxuPC9ib2R5PlxuIn0seyJuYW1lIjoicGFja2FnZS5qc29uIiwiY29udGVudCI6IntcbiAgXCJkZXBlbmRlbmNpZXNcIjoge1xuICAgIFwibGl0XCI6IFwiXjMuMC4wXCIsXG4gICAgXCJAbGl0L3JlYWN0aXZlLWVsZW1lbnRcIjogXCJeMi4wLjBcIixcbiAgICBcImxpdC1lbGVtZW50XCI6IFwiXjQuMC4wXCIsXG4gICAgXCJsaXQtaHRtbFwiOiBcIl4zLjAuMFwiXG4gIH1cbn0iLCJoaWRkZW4iOnRydWV9XQ)

**Comment by CornerSyrup** [comment]
I use a more classic way,

```css
html, body {
  min-height: 100vh;
}

/* It doesn't matter where you put your `md-fab`
   as long as you specify the correct selector */
md-fab {
  position: fixed;
  right: 16px;     /* style as you need */
  bottom: 16px;    /* style as you need */
}
```

**Comment by CarlosEGuerraSilva** [comment]
For re-usability and dev-friendly understanding I made it like this:

```css
md-fab[position]{
  position: fixed;
  &[position="bottom-left"]{
    bottom: 1rem;
    left: 1rem;
  }
  &[position="bottom-right"]{
    bottom: 1rem;
    right: 1rem;
  }
}
```
