### DISCUSSION TITLE
How can I make a dialog take up most of the window?

### DISCUSSION THREAD

**Discussion by treeder** [material-components/material-web#5375] [Q&A] [answered]
Style width and height don't seem to work on the dialog, any ideas how to do this?

**Comment by asyncliz** [comment, marked as answer]
You can use `margin` to customize where the dialog is positioned. You may also need to unset `max-width` and `max-height` if you want the dialog to be able to expand larger than those default limits.

```css
md-dialog.fullscreen {
  margin: 0;
  width: 100vw;
  height: 100vh;
  max-width: unset;
  max-height: unset;
  --md-dialog-container-shape: 0;
}
```
