### DISCUSSION TITLE
Vanilla CSS friendly tokens

### DISCUSSION THREAD

**Discussion by motss** [material-components/material-web#5439] [Q&A]
### Description

May I ask if there is a compiled version of the [typescale](https://unpkg.com/browse/@material/web@1.1.1/tokens/v0_192/_md-sys-typescale.scss) tokens for Vanilla CSS users? If no, is there a plan to output a list of CSS Custom Properties for all these tokens?

Thanks in advance.

**Comment by asyncliz** [comment]
We list the [typescale tokens in our typography doc](https://github.com/material-components/material-web/blob/main/docs/theming/typography.md#tokens-1). There is not a pre-compiled CSS or Lit stylesheet that has these tokens for usage in CSS yet, but we're working on it in https://github.com/material-components/material-web/issues/1050 [this year](https://github.com/material-components/material-web/blob/main/docs/roadmap.md#expand-material-design-tokens)!

In the meantime, you can use [Sass](https://sass-lang.com/) to compile the tokens to a CSS stylesheet yourself to use.

Create a Sass file...

```scss
// my-stylesheet.scss
@use '@material/web/typography/typescale';
@use '@material/web/tokens';

:root {
  // Emit --md-sys-typescale-* tokens to use in your own CSS
  @include typescale.theme(tokens.md-sys-typescale-values());
}

// You can now reference properties in your CSS
.my-display {
  font-family: var(--md-sys-typescale-display-medium-font);
}
```
...then download MWC and Sass to compile it...
```sh
npm install @material/web sass
npx sass --load-path=node_modules my-stylesheet.scss my-stylesheet.css
```
...and use the resulting CSS stylesheet.
```css
:root {
  --md-sys-typescale-display-medium-font: var(--md-ref-typeface-brand, Roboto);
}

.my-display {
  font-family: var(--md-sys-typescale-display-medium-font);
}
```

> Tip: you can use similar APIs for [color](https://github.com/material-components/material-web/blob/main/color/_color.scss) and [typeface](https://github.com/material-components/material-web/blob/main/typography/_typeface.scss) custom properties.

**Comment by neoacevedo** [comment]
Compiling with dart sass I get the following:
```
:root {
...
--md-sys-typescale-display-medium-font: var(--md-sys-typescale-display-medium-font, var(--md-ref-typeface-brand, Roboto));
...
}
```
But `--md-ref-typeface-brand` is not defined.

**Reply by asyncliz** [reply]
The typeface tokens are emitted from a different mixin. Here's how you'd emit both sys-typescale and ref-typeface:

```scss
// my-stylesheet.scss
@use '@material/web/typography/typescale';
@use '@material/web/typography/typeface';
@use '@material/web/tokens';

:root {
  // Emit --md-sys-typescale-* tokens to use in your own CSS
  @include typescale.theme(tokens.md-sys-typescale-values());
  // Emit --md-ref-typeface-* tokens to use in your own CSS
  @include typeface.theme(tokens.md-ref-typeface-values());
}

// You can now reference properties in your CSS
.my-display {
  font-family: var(--md-sys-typescale-display-medium-font);

  &.branded {
    font-family: var(--md-ref-typeface-brand);
  }
}
```
