### DISCUSSION TITLE
How to style outlined select component?

### DISCUSSION THREAD

**Discussion by Forseti93** [material-components/material-web#5570] [General]
I wish to use[ outlined select component ](https://material-web.dev/components/select/)with a custom css:
```
<md-outlined-select>
<md-select-option>
...

//found tokens:
--md-sys-on-primary: **;
--md-outlined-text-field-input-text-size: **;
--md-outlined-text-field-label-text-size: **;
```
How to edit colors for a dropdown menu? What tokens should I use?

**Comment by asyncliz** [comment]
You'll need to use the [outlined select's tokens](https://material-web.dev/components/select/#outlined-select-tokens), which look similar to text fields' but have a different prefix.

```css
md-outlined-select {
  --md-sys-on-primary: **;
  --md-outlined-select-text-field-input-text-size: **;
  --md-outlined-select-text-field-label-text-size: **;
}
```

For the menu, use the `::part(menu)` selector and [menu tokens](https://material-web.dev/components/menu/#menu-tokens).

```css
md-outlined-select::part(menu) {
  --md-menu-container-color: **;
}
```
