### DISCUSSION TITLE
Help finding documentation for having your application blend well with the components.

### DISCUSSION THREAD

**Discussion by GoHarder** [material-components/material-web#5688] [Q&A]
This question arose because it is possible to add some css to the window scrollbar.
The default browser scroll bar kind of clashes with the rounded design of the components.

![image](https://github.com/user-attachments/assets/7b017ffc-9bec-4570-a0d3-c464fbf88fd0)

That led me to look around to see if there was some documentation on how to have your bits of css like that blend well with the components in the library.

Is there anything like that already and I couldn't find it? 
If it doesn't exist would there be something in the pipeline for that soon?
Or do I have to just wing it the best I can?

**Comment by creamIcec** [comment]
Maybe the problem i'm facing is similar to yours. Also looking for a solution here.
The problem is about the `md-outlined-text-field` with multi-line enabled(set `type` to textarea), whose scrollbar is vanilla(by 'vanilla' I mean default to browser), and the appearance can't be modified easily by adding css following on root(index.css):
```css
textarea::-webkit-scrollbar{
  width: 8px;
  height: 8px;
}
textarea::-webkit-scrollbar-thumb{
  border-radius: 16px;
}
```
Commonly we can apply these rules to normal HTML element and it will work but not md components. Is there any token I should use instead? Or this is just not supported yet?

**Reply by GoHarder** [reply]
There is a way to kind of style the scroll bar the main limitation is that it is browser dependent. The closest I got it to work was this mix in that I found watching Kevin Powell on YouTube.

```scss
@mixin scrollbar($selector, $background-color) {
   #{$selector} {
      &::-webkit-scrollbar {
         width: 1em;
         box-sizing: content-box;
      }

      &::-webkit-scrollbar-track {
         margin-block: 0.25em;
      }

      &::-webkit-scrollbar-thumb {
         background: rgba(0, 0, 0, 0.12);
         border-radius: 1000px;
         border: 0.25em solid $background-color;
      }

      &:hover {
         &::-webkit-scrollbar-thumb {
            background: rgba(0, 0, 0, 0.24);
         }
      }
   }

   @supports (scrollbar-color: rgba(0, 0, 0, 0.12) rgba(0, 0, 0, 0)) {
      #{$selector} {
         scrollbar-color: rgba(0, 0, 0, 0.12) rgba(0, 0, 0, 0);
         scrollbar-width: thin;

         &:hover {
            scrollbar-color: rgba(0, 0, 0, 0.24) rgba(0, 0, 0, 0);
         }
      }
   }
}
```
Since this library uses web components the styles are encapsulated within the component. The good thing is that you can add CSS variables and get the customization you need. If you need something that is outside the variables then you need to peel open the web and hand roll your own with the modified CSS.
