### ISSUE TITLE
unable to listen to clicks on textfield icon (trailing and leading)

### ISSUE THREAD

**Issue by christophe-g** [material-components/material-web#2447]
**Describe the bug**

It is not possible to listen to a click event on a textfield icon as this style is being applied on icons : 

```css
.mdc-text-field__icon:not([tabindex]), .mdc-text-field__icon[tabindex="-1"] {
    cursor: default;
    pointer-events: none;
}
```

**Expected behavior**

Listenting to a click event should be able to tell if an icon was clicked
```html
<mwc-textfield label=label trailingIcon=delete @click=${this.onDelete}></mwc-textfield>
```

```js
 onDelete(e) {
  const clickedElement = e.composedPath()[0]; 
}
```

**Workaround** 
Extend textfield and override the above style or `renderIcon` method to add `tabindex=0` to the icon.
