### ISSUE TITLE
mwc-textfield label clipped when font-size changed

### ISSUE THREAD

**Issue by andreinocenti** [material-components/material-web#2840]
**Describe the bug**

When the  --mdc-typography-subtitle1-font-size: is changed the input label is clipped when the textfield is "filled" or with focus.

When the field is not focused or not filled
![image](https://user-images.githubusercontent.com/39701679/137191094-9c82a55a-6959-41c1-a1b9-973c1107b82e.png)

When the field is focused or filled.
![image](https://user-images.githubusercontent.com/39701679/137191194-f84ae358-abe1-4062-9aa2-e9cf9bd4f035.png)

I have tried the textfield.layout() with several different approachs. I tried set it with timeout or when the field is focused and no lucky.

**To Reproduce**

Set the css below to change the mwc-textfield font-size, it was too big with the new font that i must use.

```css
mwc-textfield{
    --mdc-typography-font-family: "Comfortaa";
    --mdc-typography-subtitle1-font-size: "14px";
}
```

**Expected behavior**

To show the label without clip the text

**Browser Version (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
