### ISSUE TITLE
Drawer should not hard code colors

### ISSUE THREAD

**Issue by Oloompa** [material-components/material-web#2955]
**Describe the bug**
Title and subtitle in drawer have a hard-coded color

```css
.mdc-drawer .mdc-drawer__title {
 color:rgba(0, 0, 0, 0.87);
}
```

**To Reproduce**
1. setup a dark mode
2. text is unreadable

**Expected behavior**
slotted text should use `--mdc-theme-on-surface` variable for font color.
