### ISSUE TITLE
Default font family should be present

### ISSUE THREAD

**Issue by csudarshan259** [material-components/material-web#4315]
Hi,
After bundling using rollup I had to explicitly set up Roboto Font Family.

**Comment by asyncLiz** [comment]
Can you provide a reproduction link? The default font family should be present in the fallbacks

**Comment by treeder** [comment]
How do you set the default font family?

**Comment by asyncLiz** [comment]
You can set [`--md-sys-typescale-*` CSS custom properties](https://github.com/material-components/material-web/blob/447886da2e5c648837704a3fc7a4552b5ba6e80a/tokens/_md-sys-typescale.scss#L19-L33) as well as [`--md-ref-typeface-*` CSS custom properties](https://github.com/material-components/material-web/blob/447886da2e5c648837704a3fc7a4552b5ba6e80a/tokens/_md-ref-typeface.scss#L15-L16)

```css
:root {
  --md-ref-typeface-plain: 'Open Sans';
  --md-ref-typeface-brand: 'Open Sans'
}
```

**Comment by treeder** [comment]
What's an example of setting a typescale, like what values does it take? 

```
md-sys-typescale-body-large: ???;
```

Also, I figured out why my Roboto wasn't working, it's because I didn't import weight 500. Apparently the md components use that specific weight.

**Comment by asyncLiz** [comment]
It takes a [`font` shorthand value](https://developer.mozilla.org/en-US/docs/Web/CSS/font).

Use the typescale custom properties when you want to change more than just the font family, such as font sizes and line heights.

```css
:root {
  /* Sets font-family, font-size, and line-height */
  --md-sys-typescale-body-large: 'Open Sans' 24px/32px;
}
```
