### ISSUE TITLE
unable to set icon font settings at global scope (pre.15)

### ISSUE THREAD

**Issue by christophe-g** [material-components/material-web#4679]
https://github.com/material-components/material-web/commit/ff60a88843f901eb553e271fb5a786d6439935c8#diff-6c61e56eda07ace104589c1790597eb6d918bb0b6460b31066ffef4de43eace7 seems to break the possibility to set icon font settings at global scope. 

Prior to this, it was possible to make all icons as filled by default:
```css
:root {
  --md-icon-font-variation-settings: 'FILL' 1;
}
```

The recommended way would now be:
```css
:root {
 font-variation-settings: 'FILL' 1;
}
```

As `font-variation-settings` does not seem to be a css proprerty that inherits, icons in other elements (e.g. icons in shadow-dom of buttons, or fab) do not inherits from `:root` settings - and hence are not filled.
