### ISSUE TITLE
If you set style.display on a button, it loses it's contents

### ISSUE THREAD

**Issue by treeder** [material-components/material-web#5309]
### What is affected?

Component, Theming

### Description

This just started with the latest release. For instance, try to use:

```
 .expanded {
      display: unset;
 }
```

Or `display: block;`, your button will just be blank:

![image](https://github.com/material-components/material-web/assets/75826/fe88ed28-7aa2-4d04-95b7-f8d9b24d29f8)

From the looks of it, it starts as an `inline-flex`. 

I think the solution for this is probably to add an outer div around the buttons so the outermost element isn't the required flex element. 

### Reproduction

```html
<md-filled-button class="expanded" href="/new" >New</md-filled-button>
```

```css
  .expanded {
      display: unset;
 }
```

### Workaround

Could add my own div around all my buttons. 

### Is this a regression?

Yes. This used to work, but now it doesn't.

### Affected versions

1.1.X

### Browser/OS/Node environment

ChromeOS 119.

**Comment by asyncLiz** [comment]
This is working as intended. Removing or changing the default display type is not supported.

You can however swap between flex and inline flex displays for components.

**Comment by treeder** [comment]
Ok, this does appear to be a breaking regression though and it wasn't in the change logs. 

Anyways, any recommendations on how to deal with media queries that show/hide these material components as you resize, since you can't easily do it now?  Like should we wrap every component in our own div or span or something so we can hide/show them?

**Comment by asyncLiz** [comment]
`display: none` can be used to hide the elements. It is necessary to layer `display: unset` to re-show the element? Or could the media query only hide it when necessary?

**Comment by treeder** [comment]
If you only hide it, then the problem is it won't show it again if you resize your window. The other problem with only hiding is if you have an element that you want to show at a couple of different sizes, for example let's say you have medium and expanded classes like `class="medium expanded"`, if one of this is `display: none` based on the size, it won't show up for either.

This is what we have that worked up until 1.1.X:

```css
.compact {
    display: none;
}

.medium {
    display: none;
}

.expanded {
    display: none;
}

@media screen and (max-width: 599px) {
    .compact {
        display: block;
    }
}

@media screen and (min-width: 600px) and (max-width: 839px) {
    .medium {
        display: block;
    }
}

@media screen and (min-width: 840px) {
    .expanded {
        display: block;
    }
}
```

display: unset also worked (probably because it might do the same thing as display: block).

**Comment by asyncLiz** [comment]
This problem exists in all UI libraries that add CSS `display` on their components, since you cannot `display: unset` to a previous stylesheet's value. It resets completely to the browser's default.

Your media query logic turns everything off by default, meaning components lose the display added by their stylesheets with no way to revert it.

Instead, the logic can be refactored to show by default and only hide with `display: none` when the media query matches. This would be the right approach to preserve a library's default CSS.

```css
@media screen and (max-width: 599px) {
    :is(.medium, .expanded):not(.compact) {
        display: none;
    }
}

@media screen and (min-width: 600px) and (max-width: 839px) {
    :is(.compact, .expanded):not(.medium) {
        display: none;
    }
}

@media screen and (min-width: 840px) {
    :is(.compact, .medium):not(.expanded) {
        display: none;
    }
}
```
