### ISSUE TITLE
Setting individual shape to outlined text field fails if unit is not set

### ISSUE THREAD

**Issue by shadow-identity** [material-components/material-web#5443]
### What is affected?

Component

### Description

I need to set a shape of the `md-outlined-text-field` to have rounded top angles but not rounded bottom ones when active. But it does not work if unit is not specified in css custom property which controls the shape.

### Reproduction

I need to set a shape of the md-outlined-text-field to have rounded top angles and not rounded bottom.
So I set the default shape and override the bottom corners: 
 ```css
    md-outlined-text-field {
        --md-outlined-text-field-container-shape: 1.7rem;
    }
    md-outlined-text-field:focus {
        --md-outlined-text-field-container-shape-end-start: 0;
        --md-outlined-text-field-container-shape-end-end: 0;
    }
```
But it results in broken shape of the component: not only the top left corner has the radius of 0, but also the left padding / margin completely disappeared: 
<img width="131" alt="image" src="https://github.com/material-components/material-web/assets/1223112/1d1e35b7-2197-45e2-b308-f34589ee3322">

### Workaround

I found that if I set units explicitly (0px or 0rem) it works.
```css
    md-outlined-text-field:focus {
        --md-outlined-text-field-container-shape-end-start: 0rem;
        --md-outlined-text-field-container-shape-end-end: 0px;
    }
```

<img width="154" alt="image" src="https://github.com/material-components/material-web/assets/1223112/368e5445-2e5f-4b7d-9dae-8dec434a44ab">

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

Failing on 1.2.0

### Browser/OS/Node environment

Firefox 123.0b4 (64-bit)
mas OS 14.3 (23D56)
node v18.14.0
