### ISSUE TITLE
Text button cannot display the specified color correctly

### ISSUE THREAD

**Issue by mai1202** [material-components/material-web#5520]
### What is affected?

Component

### Description

When I use `md-text-button` which specifies the `--md-text-button-label-text-color` color, it cannot display the specified color, but displays the `--md-sys-color-primary` color when the mouse pointer is hovered or clicked.

![image](https://github.com/material-components/material-web/assets/63698132/616214ce-836e-4cd9-8dc8-8b7b8ec88bc0)
Normally
![image](https://github.com/material-components/material-web/assets/63698132/55192976-c7fc-49ee-b864-a1e9771f765c)
Hover
![image](https://github.com/material-components/material-web/assets/63698132/4b4fc65d-6e01-42ba-bec7-b0c569e3b95a)
Active

```
:root {--md-sys-color-primary: green;}
md-text-button {--md-text-button-label-text-color: #ba1a1a;}
```

### Reproduction

https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy5qcyIsImNvbnRlbnQiOiJpbXBvcnQgJ0BtYXRlcmlhbC93ZWIvYWxsLmpzJztcbiJ9LHsibmFtZSI6ImluZGV4Lmh0bWwiLCJjb250ZW50IjoiPCFET0NUWVBFIGh0bWw-XG48aGVhZD5cbiAgPHNjcmlwdCB0eXBlPVwibW9kdWxlXCIgc3JjPVwiLi9zaW1wbGUtZ3JlZXRpbmcuanNcIj48L3NjcmlwdD5cbiAgPHN0eWxlPlxuICAgIDpyb290IHtcbiAgICAgIC0tbWQtc3lzLWNvbG9yLXByaW1hcnk6IGdyZWVuO1xuICAgIH1cbiAgICBcbiAgICBtZC10ZXh0LWJ1dHRvbiB7XG4gICAgICAtLW1kLXRleHQtYnV0dG9uLWxhYmVsLXRleHQtY29sb3I6ICNiYTFhMWE7XG4gICAgfVxuICA8L3N0eWxlPlxuPC9oZWFkPlxuPGJvZHk-XG4gIDxzaW1wbGUtZ3JlZXRpbmcgbmFtZT1cIldvcmxkXCI-PC9zaW1wbGUtZ3JlZXRpbmc-XG4gIDxtZC10ZXh0LWJ1dHRvbj5hPC9tZC10ZXh0LWJ1dHRvbj5cbjwvYm9keT5cbiJ9LHsibmFtZSI6InBhY2thZ2UuanNvbiIsImNvbnRlbnQiOiJ7XG4gIFwiZGVwZW5kZW5jaWVzXCI6IHtcbiAgICBcImxpdFwiOiBcIl4zLjAuMFwiLFxuICAgIFwiQGxpdC9yZWFjdGl2ZS1lbGVtZW50XCI6IFwiXjIuMC4wXCIsXG4gICAgXCJsaXQtZWxlbWVudFwiOiBcIl40LjAuMFwiLFxuICAgIFwibGl0LWh0bWxcIjogXCJeMy4wLjBcIlxuICB9XG59IiwiaGlkZGVuIjp0cnVlfV0

### Workaround

I have not found a workaround.

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

1.3.0

### Browser/OS/Node environment

Chrome 122.0.6261.112

**Comment by asyncLiz** [comment]
This is intentional, but a little confusing. See the ["How do I change the color of a button?"](https://github.com/material-components/material-web/blob/main/docs/support.md#how-do-i-change-the-color-of-a-button) and ["Why does my color change on hover/focus/pressed?"](https://github.com/material-components/material-web/blob/main/docs/support.md#why-does-my-color-change-on-hoverfocuspressed) FAQs.

The tl;dr is that there are more custom properties you need to set.

```css
:root {
  --md-sys-color-primary: green;
}

md-text-button {
  --md-text-button-label-text-color: #ba1a1a;
  --md-text-button-hover-label-text-color: #ba1a1a;
  --md-text-button-focus-label-text-color: #ba1a1a;
  --md-text-button-pressed-label-text-color: #ba1a1a;
}
```

Or alternatively, set a single system property on the text button that these custom properties map to (primary).

```css
:root {
  --md-sys-color-primary: green;
}

md-text-button {
  --md-sys-color-primary: #ba1a1a;
}
```

We recommend setting system properties when possible, since there are a lot of component properties to update, like backgrounds, outlines, and ripple states.
