### ISSUE TITLE
Minor FR: A sane sans serif font

### ISSUE THREAD

**Issue by omar2205** [material-components/material-web#5526]
### Description

Currently, if I don't load Roboto the components don't have a _sane_ default font.

![image](https://github.com/material-components/material-web/assets/1373867/15028be1-3ca5-4c10-8709-25d9f92ef5df)

```css
  font-family: Helvetica, Arial, Sans-Serif;

  /* or even this would be better */

  font-family: Sans-Serif;

```

**Comment by asyncLiz** [comment]
Thanks for the issue! This is possible using the [`--md-ref-typeface-*` tokens](https://github.com/material-components/material-web/blob/main/docs/theming/typography.md#tokens).

```css
:root {
  --md-ref-typeface-brand: Helvetica, Ariala, sans-serif;
  --md-ref-typeface-plain: sans-serif;
}
```

We don't inject fallback fonts from the default Roboto since font fallback choice and order is opinionated and different for each project.
