### ISSUE TITLE
problem displaying the ripple on the outlined button

### ISSUE THREAD

**Issue by Benoit-ROBIN** [material-components/material-web#5620]
### What is affected?

Component, Theming

### Description

When I try to change the style of `md-outlined-button` I have displaying issues.
When I change this value : 
```scss
.button-outlined {
  --md-ripple-pressed-opacity: 1;
}
```
there is a white border inside the button
<img width="293" alt="Capture d’écran 2024-05-14 à 17 09 00" src="https://github.com/material-components/material-web/assets/5525003/4699d1dd-628d-48b4-9566-e6c4e92704fd">

The problem is because of mismatching border lines, which causes the ripple's border to not perfectly line up with a border on its parent.

### Workaround

A workaround was found by overriding the ripple border-radius value:
```scss
.button-outlined::part(ripple) {
  border-radius: calc(var(--eds-button-outlined-border-radius) - 1px);
}
```
to do this I need to add the attribute `part` to `md-ripple` in the `button` component.
source: https://discord.com/channels/259087343246508035/1239956071762624563

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

1.4.1

### Browser/OS/Node environment

node: 18.12.1
npm: 8.19.2
chrome: 124.0.6367.208
macos: 14.2.1
