### ISSUE TITLE
Research extensibility

### ISSUE THREAD

**Issue by govis** [material-components/material-web#602]
We tried extending <code>TabBarBase</code> to activate tab by its' id as opposed to index. To do this one needs access to <code>\_getTabs</code> method, but it's private and call <code>getIndexOfTabById</code>, which is buried in <code>mdcFoundation.adapter_</code> and is not accessible either

**Comment by kr05** [comment]
Most of these components are hard to extend. From personal experience, I've gone through so much trouble customizing:

mwc-button
mwc-textfield
mwc-fab
mwc-drawer
mwc-radio
mwc-switch

and probably a couple more I forgot. Most of the times, I simply make the changes locally and simply make sure I remember to use the same machine to build the project.

Here's an example of a simple change I made to the css file for mwc-drawer:
```css
.mdc-drawer-app-content {
  /* Default styles */
  margin-left: 0;
  margin-right: 0;
  position: relative;

  /* Added style */
  width: 100%;
}
```
On more important client projects, I have unfortunately been forced to either accept the component for what it is, or choose an alternative.
